# Generated by Django 4.2.8 on 2023-12-20 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Место')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)], verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Текст поста')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Места',
                'verbose_name_plural': 'Места',
                'ordering': ['-time_created'],
                'indexes': [models.Index(fields=['-time_created'], name='places_plac_time_cr_992c04_idx')],
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='ФИО человека')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_posts', to='places.place', verbose_name='Место рождения')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='places_peop_name_0284f2_idx')],
            },
        ),
    ]
