# Generated by Django 4.2.8 on 2023-12-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
