# Generated by Django 4.2.8 on 2023-12-20 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_remove_place_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['time_created'], 'verbose_name': 'Места', 'verbose_name_plural': 'Места'},
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
