# Generated by Django 4.2.1 on 2023-12-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-time_created']},
        ),
    ]
