# Generated by Django 4.2.1 on 2023-12-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('biography', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-time_created'], name='places_plac_time_cr_992c04_idx'),
        ),
        migrations.AddField(
            model_name='place',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='places.people'),
        ),
    ]
