# Generated by Django 4.2.1 on 2023-12-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_people_place_places_plac_time_cr_992c04_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.people'),
        ),
    ]
