# Generated by Django 4.2.1 on 2023-12-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_people_people_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_posts', to='places.place'),
        ),
    ]
