# Generated by Django 4.2.1 on 2023-12-14 11:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_people_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['name'], 'verbose_name': 'Человека', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='people',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ФИО человека'),
        ),
        migrations.AlterField(
            model_name='people',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_posts', to='places.place', verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='place',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='place',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AddIndex(
            model_name='people',
            index=models.Index(fields=['name'], name='places_peop_name_0284f2_idx'),
        ),
    ]
