# Generated by Django 4.2.1 on 2023-12-20 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0013_alter_people_options_alter_place_options_people_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='place',
            name='places_plac_time_cr_992c04_idx',
        ),
        migrations.AddField(
            model_name='place',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['time_created'], name='places_plac_time_cr_47a372_idx'),
        ),
    ]
